# -*- coding: utf-8 -*-
"""Mirea1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRjBVF7v3Sc8jibssd1xZmoJ81wt_Imh
"""

import math

def f(x):
  return 3 * x - 4 * math.log(x) - 5

l_start = 2
r_start = 4
l = l_start
r = r_start

# половинное деление
while r - l > 0.0001: # ищем бинпоиском корень, каждую итерацию уменьшая область поиска в 2 раза
  m = (l+r)/2
  if (f(r_start) > f(l_start)): # проверяем, возрастает или убывает функция
    if f(m) > 0:
      r = m
    else:
      l = m
  else:
    if f(m) < 0:
      r = m
    else:
      l = m
print(m)

# метод хорд
l = 2
r = 4
for i in range(200): # чем больше кол-во итераций, тем точнее будет результат
  l = l - (r-l)*f(l)/(f(r)-f(l))
print(l)

# защитил